### PR TITLE
Updated Dawn Test

### PR DESCRIPTION
**Pull request by paarongiroux**

### CODE REVIEW

**Comment by paarongiroux** [comment]
I'm getting a `No Such Driver for Label` exception in the load test after my latest commit, not sure why this is happening

**Comment by jessemapel** [comment]
Try directly instantiating the driver and calling the formatter on it.

**Comment by jessemapel** [comment]
This is still missing the SPK, `*.xsp`

**Comment by kberryUSGS** [comment]
Try pulling down master. Looks like this is failing now because the light time correction for sun was re-added in a different PR so you're getting different calculated values for sun position/velocity.

**Pull request merged**
