### PR TITLE
Added code to account for ISIS ccd center

### PR DESCRIPTION
**Pull request by jessemapel**
ISIS uses 0.5 based detector pixels so all the drivers that use the '_BORESIGHT` keywords need to subtract 0.5 to convert to 0 based detector pixels. The exception is that line scan instruments use 0 based detector lines. The drivers that use the `CCD_CENTER` keywords need to account for whatever is defined in the kernels. For example Dawn FC has -0.5 based Detector coordinates.

### CODE REVIEW

**Comment by kaitlyndlee** [comment]
Is this only for ctx or other line scanners?

**Comment by jessemapel** [comment]
@kaitlyndlee This is for anything that uses [LineScanCameraDetectorMap](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/base/objs/LineScanCameraDetectorMap/LineScanCameraDetectorMap.cpp#L144)

from some prelimenary grepping that is
* LROC NAC
* Chandrayaan1 M3
* Themis IR
* Rosetta Virtis
* MOC NAC
* Apollo Panoramic Camera
* CTX
* HiRISE
* CRISM
* LEISA
* MVIC
* Kaguya MI
* Dawn VIR
* HRSC
* Ideal Line Scan

**Comment by jessemapel** [comment]
So I looked at [VariableLineScanCameraDetectorMap](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/base/objs/VariableLineScanCameraDetectorMap/VariableLineScanCameraDetectorMap.cpp#L130) and it looks like it dispatches to [CameraDetectorMap](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/base/objs/CameraDetectorMap/CameraDetectorMap.cpp#L98) which appears to be 0 based?

**Comment by scsides** [comment]
That's what we agreed on

**Pull request merged**
