### PR TITLE
Crism driver DRAFT

### PR DESCRIPTION
**Pull request by amystamile-usgs**
Draft PR for Crism driver currently ale is successfully generating isd and isis is picking up ale when running spiceinit.

TODOs:

- [ ] create transfer files for testing.
- [ ] finish writing tests.

### CODE REVIEW

**Comment by amystamile-usgs** [comment]
> Currently running into this error:
> 
> Screen Shot 2022-03-11 at 10 19 19 AM

Determined that ikid was returning `-74010`.  Overwritten ikid to return `-74017` from `self.label['IsisCube']['Kernels']['NaifIkCode']` and now get this error:

image

**Comment by acpaquette** [comment]
We have had to correct frame issues in ISIS camera models and this looks similar to that. I would check the ingestion app for crism and the crism camera model in ISIS for any custom additions

**Comment by amystamile-usgs** [comment]
Currently running into the following error when running KernelSlice.ipynb. Also seeing table differences between ale's spiceinit cube and isis's spiceinit cube. Not sure what to look for in these differences.

Screen Shot 2022-03-14 at 10 11 49 AM

**Comment by jessemapel** [comment]
I will be modifying the repo history as part of #440, if this PR is ready to go please flag it as such and we can get it merged before I modify the history. Otherwise, it will need to be rebased onto the new master branch.

I can preform the re-base if you allow maintainers permission to modify your PR.

**Pull request closed without merging**
