### PR TITLE
Pfeffernusse Loading Fixes

### PR DESCRIPTION
**Pull request by acpaquette**
Changes necessary to get Pfeffernusse and ALE cooperating

- Allow ALE to find both caps and not caps metakernels
- Remove special sensor_frame_id from cassini (Fixed via a kernel update)
- If your label is a PVLModule don't also attempt to load it as if it were a file

### CODE REVIEW

**Comment by acpaquette** [comment]
@jessemapel I didn't hit the merge button before pushing 😬Needs another review

**Comment by jessemapel** [comment]
Cassini load test appears to be failing :(

**Comment by jessemapel** [comment]
Here's the text for the extra Cassini rotations from the kernels.

NAC:

```
\begintext

The Cassini ISS NAC frames kernel is missing one final rotation in its
CK frames hierarchy.  A 180 degree rotation about the detector center
(Z-axis) is required to map into the proper detector orientation.  This
is not included in the NAIF SPICE frames kernel (cas_v??.tf).  The following
frames definition applies the rotation into camera coordinates and must
be the frame used in the ISIS camera model converting from the s/c frame to
the instrument. (KJB, 2009-01-22)

\begindata
INS_-82360_FRAME_ID           = 14082360
FRAME_CASSINI_ISS_NAC_USGS    = 14082360
FRAME_14082360_NAME           = 'CASSINI_ISS_NAC_USGS'
FRAME_14082360_CLASS          = 4
FRAME_14082360_CLASS_ID       = 14082360
FRAME_14082360_CENTER         = -82
TKFRAME_14082360_SPEC         = 'ANGLES'
TKFRAME_14082360_RELATIVE     = 'CASSINI_ISS_NAC'
TKFRAME_14082360_ANGLES       = (0.0,       0.0,    180.0)
TKFRAME_14082360_AXES         = (  1,         2,        3)
TKFRAME_14082360_UNITS        = 'DEGREES' 
```

WAC:

```
\begintext

The Cassini ISS WAC frames kernel is missing one final rotation in its
CK frames hierarchy.  A 180 degree rotation about the detector center
(Z-axis) is required to map into the proper detector orientation.  This
is not included in the NAIF SPICE frames kernel (cas_v??.tf).  The following
frames definition applies the rotation into camera coordinates and must
be the frame used in the ISIS camera model converting from the s/c frame to
the instrument. (KJB, 2009-01-22)

\begindata

INS_-82361_FRAME_ID           = 14082361
FRAME_CASSINI_ISS_WAC_USGS    = 14082361
FRAME_14082361_NAME           = 'CASSINI_ISS_WAC_USGS'
FRAME_14082361_CLASS          = 4
FRAME_14082361_CLASS_ID       = 14082361
FRAME_14082361_CENTER         = -82
TKFRAME_14082361_SPEC         = 'ANGLES'
TKFRAME_14082361_RELATIVE     = 'CASSINI_ISS_WAC'
TKFRAME_14082361_ANGLES       = (0.0,       0.0,    180.0)
TKFRAME_14082361_AXES         = (  1,         2,        3)
TKFRAME_14082361_UNITS        = 'DEGREES' 
```

I think we need to code these rotations into the Cassini driver for when the IAK is not available.

**Comment by jessemapel** [comment]
Looking at the latest [Cassini FK](https://naif.jpl.nasa.gov/pub/naif/CASSINI/kernels/fk/cas_v42.tf), these rotations are not present in the latest PDS kernel release. So, we need these hardcoded in the driver for when the IAK is not available.

**Pull request merged**
