### PR TITLE
Update Spacecraft Position

### PR DESCRIPTION
**Pull request by kberryUSGS**
Updated spacecraft_position by fixing the order of the arguments to `spkezr` and negate resulting vector so it still points the correct direction.

### CODE REVIEW

**Comment by acpaquette** [comment]
Weird mac faliure, restarted the mac test all should be good though

**Comment by kberryUSGS** [comment]
@acpaquette Do you need special permissions to restart the build? I didn't see any way to do this.

**Comment by acpaquette** [comment]
@kberryUSGS Potentially? I would just double check that your logged into travis and that your github is linked to it. Outside of that I'm not sure

**Comment by kberryUSGS** [comment]
@acpaquette I indeed wasn't logged into Travis. Thanks!

**Pull request merged**
