### PR TITLE
Updated generate_kernels_from_cube docs

### LINKED ISSUE #497: ISIS Dependency
When using `util.generate_kernels_from_cub`, the ALE library throws an error if ISISROOT is not set. (I am using this function as a work around to #495.) This seems to indicate that ISIS is a dependency if one is going to be getting kernels from ISIS cubes. Is ISIS a necessary dependency of ALE? If so, can it be added to the environment.yml? If not, is it possible to refactor so that the above utility is usable without setting ISISROOT? Thanks!

### PR DESCRIPTION
**Pull request by jessemapel**
Added notes about usage of the ISISROOT environment variable.

Fixes #497

### CODE REVIEW

**Review by jlaura — APPROVED** [review]

**Comment by jlaura** [comment]
Look good. I reran the failed jobs. They looked like conda related issues and not something having to do with the doc change.

**Comment by jessemapel** [comment]
Yeah we're having issue with conda timing out when we run a whole bunch of CI jobs. It's rather annoying.

**Comment by jlaura** [comment]
Everything except py3.7 passed. I'm comfortable with this merging as it's still a conda issue. I'll leave it up to you if you want to mess with the CI more.

**Comment by jessemapel** [comment]
Yeah, the Py3.7 environment must be having issues. It's not related to this doc update, though.

**Pull request merged**
