### PR TITLE
Updated Mini RF to use the unified formatter

### PR DESCRIPTION
**Pull request by jessemapel**
I checked the new test output and it looks correct, but I want to test it out ~in a sensor model~ more before this gets merged.

### CODE REVIEW

**Comment by jessemapel** [comment]
I checked the ephemerides in this against ISIS and there are lining up. So, I'm going to say this is ready to go.

**Comment by jessemapel** [comment]
Once the USGSCSM work is done I've got a knoten comparison notebook I'm working on too that I'll put up.

**Comment by jessemapel** [comment]
@acpaquette The json ISD didn't get removed, it just got greatly reduced because I made the image smaller. It went from 10,000 lines to a few hundred.

**Comment by acpaquette** [comment]
Oh, my bad. I didn't try to actually load the diff. Looks all good then!

**Pull request merged**
